### ISSUE TITLE
Linker error when I try to build example program

### ISSUE THREAD

**Issue by ghost** [nykytenko/onyx-serial#1]
```
import onyx.serial;

void main()
{
        /* Create ports */
    auto port1 = OxSerialPort("/dev/ttyS1", 9600, "none", 10);
    auto port2 = OxSerialPort("/dev/ttyS2", 9600, "none", 10);

    port1.open;
    port2.open;

    ubyte[] data = [0x22, 0x33, 0xCC];

    port1.write(data);

    ubyte[] buf = port2.read(3);

    assert (buf == data);

    port1.close();
}
```

Hello. I changed main.d like this and when I  try to compile program using dub I get linker errors like this.

> $ dub
> Package onyx-config can be upgraded from 2.0.3 to 2.0.4.
> Use "dub upgrade" to perform those changes.
> Performing "debug" build using dmd for x86.
> onyx-config 2.0.3: target for configuration "library" is up to date.
> onyx-serial 0.3.4: target for configuration "test" is up to date.
> To force a rebuild of up-to-date targets, run again with --force.
> Running ./bin/onyx-serial 
> ## onyx.serial.SerialPortSetupException@std/stdio.d(3969): Can't setup serial port (Input/output error)
> 
> source/onyx/serial.d:503 core.sys.posix.termios.termios onyx.serial.PosixImpl.getTermios() [0x80d01ef]
> source/onyx/serial.d:473 void onyx.serial.PosixImpl.setFlags() [0x80d010f]
> source/onyx/serial.d:406 void onyx.serial.PosixImpl.setup() [0x80cfed1]
> source/onyx/serial.d:196 bool onyx.serial.OxSerialPort.open() [0x80cf8a7]
> test/main.d:14 _Dmain [0x80d793f]
> ??:? _D2rt6dmain211_d_run_mainUiPPaPUAAaZiZ6runAllMFZ9__lambda1MFZv [0x80e6f92]
> ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])*).tryExec(scope void delegate()) [0x80e6ef5]
> ??:? void rt.dmain2._d_run_main(int, char**, extern (C) int function(char[][])_).runAll() [0x80e6f4e]
> ??:? void rt.dmain2._d_run_main(int, char__, extern (C) int function(char[][])_).tryExec(scope void delegate()) [0x80e6ef5]
> ??:? _d_run_main [0x80e6e7e]
> ??:? main [0x80d7a53]
> ??:? __libc_start_main [0x1294d2]
> Program exited with code 1

Any ideas? Thanks.

**Comment by ghost** [comment]
Ok I recognized that the program is executed. So this is an invalid bug report. I close the issue.

**Comment by nykytenko** [comment]
Thank, erdemoncel.
