### ISSUE TITLE
Parity enum enforced in constructor?

### ISSUE THREAD

**Issue by Dechcaudron** [nykytenko/onyx-serial#3]
Nice library you made here :)

I was thinking, wouldn't it make much more sense to pass a Parity member instead of a string to specify the parity type? It would be way more typo-proof.

Kind of the same for the BaudRate, since it only makes sense to specify a standard value, accepting an arbitrary integer as a parameter can confuse the code user.

What do you think? Should I do it myself? Any against points?

**Comment by nykytenko** [comment]
Good suggestion, I deal with this.

**Comment by nykytenko** [comment]
Parity and BaudRate as enum in port constructor now.

**Comment by Dechcaudron** [comment]
Great! Thank you!
