### ISSUE TITLE
Allow the read method to block for input

### ISSUE THREAD

**Issue by Dechcaudron** [nykytenko/onyx-serial#4]
I've been reading the code around and the read method is works nicely unless you are expecting to read something at an unknown time. I feel that it is relevant to allow the code user to block while the method is unable to read anything (I myself am currently in need of that feature).

I have a pretty good idea about the implementation, so I can do it myself. Interested in a pull request to include this in v4.0?

**Comment by nykytenko** [comment]
> Interested in a pull request to include this in v4.0?

Interested.

**Comment by Dechcaudron** [comment]
> Interested.

Dope, there it goes.

**Comment by nykytenko** [comment]
Resolved with #6 .
